/**
 * SignalCard — displays the AI signal generated by the signal-engine service.
 *
 * Signal badge colors
 * ───────────────────
 *   BUY   green  (bg-green-600)  — model expects upward move within horizon
 *   HOLD  yellow (bg-yellow-500) — already in a position; do not add or exit
 *   WAIT  amber  (bg-orange-500) — conditions unclear; stand aside
 *   SELL  red    (bg-red-600)    — model expects downward move; exit or short
 *
 * Signal fields
 * ─────────────
 *   signal            BUY | SELL | HOLD | WAIT
 *   confidence        0–100 composite TA score (higher = stronger conviction)
 *   bullish_probability  0–1 XGBoost ML output (displayed as %)
 *   horizon           SWING (days–weeks) | POSITION (weeks–months) | GROWTH (momentum)
 *   reasons           Detailed breakdown object (see Reasons type below)
 *
 * Reasons breakdown (buildReasons)
 * ─────────────────────────────────
 * Factors are rendered as a vertical list, each with a ▲ (bullish) or
 * ▼ (bearish) indicator.  Order of display:
 *   1. Earnings proximity warning  (critical/caution/note) — shown first
 *   2. Market regime (bear market flag)
 *   3. Death cross event
 *   4. Weekly timeframe alignment  (v3: multi-timeframe confirmation)
 *   5. Active chart patterns        (v3: bull_flag, cup_and_handle, etc.)
 *   6. VWAP (20d)                   (v3: price vs institutional average)
 *   7. Trend vs SMA 50
 *   8. SMA 50 vs SMA 200 / Golden Cross
 *   9. RSI (14)
 *  10. Stochastic RSI
 *  11. MACD histogram
 *  12. ADX (trend strength)
 *  13. OBV (volume confirmation)
 *  14. ML Model (XGBoost bullish probability)
 *  15. TA composite score (footer)
 *
 * v3 signal engine enhancements reflected here:
 *   • weekly_alignment / weekly_ta_score  — ±12–15% confidence adjustment
 *   • active_patterns / pattern_adjustment — chart pattern fusion score
 *   • price_above_vwap / vwma_20          — volume-weighted trend context
 *   • days_to_earnings / earnings_warning — proximity penalty (critical/caution/note)
 */
import type { Signal } from '@/lib/api';

const SIGNAL_COLOR: Record<string, string> = {
  BUY:  'bg-green-600',
  HOLD: 'bg-yellow-500',
  WAIT: 'bg-orange-500',
  SELL: 'bg-red-600',
};

type Reasons = {
  trend_above_sma50?: boolean;
  sma50_above_sma200?: boolean;
  golden_cross_event?: boolean;
  death_cross_event?: boolean;
  gc_spread_expanding?: boolean;
  gc_spread_pct?: number | null;
  rsi?: number | null;
  stoch_rsi_k?: number | null;
  stoch_rsi_oversold?: boolean;
  stoch_rsi_overbought?: boolean;
  stoch_rsi_cross_up?: boolean;
  rsi_divergence?: string;
  macd_hist?: number | null;
  macd_rising?: boolean;
  macd_hist_expanding?: boolean;
  macd_momentum_fading?: boolean;
  macd_hist_slope?: number | null;
  macd_zero_cross_up?: boolean;
  bb_pct_b?: number | null;
  adx?: number | null;
  adx_bullish?: boolean;
  obv_trend_bullish?: boolean;
  volume_z?: number | null;
  ml_probability?: number | null;
  market_regime?: string;
  ta_score?: number | null;
  // pillar scores (SA-19)
  pillar_trend?: number | null;
  pillar_momentum?: number | null;
  pillar_volume?: number | null;
  pillar_structure?: number | null;
  independent_pillars_active?: number | null;
  // v3 additions
  price_above_vwap?: boolean | null;
  vwma_20?: number | null;
  weekly_ta_score?: number | null;
  weekly_alignment?: boolean | null;
  weekly_rsi?: number | null;
  weekly_trend?: string | null;
  weekly_macd_bull?: boolean | null;
  weekly_gate_fired?: boolean | null;
  active_patterns?: string[];
  pattern_adjustment?: number | null;
  days_to_earnings?: number | null;
  earnings_warning?: string;
  // v4 additions
  ml_ta_conflict?: boolean;
  adx_compression?: boolean;
  high_vol_compression?: boolean;
  fear_greed_score?: number | null;
  // v5 additions
  sr_context?: string | null;
  sr_flag?: string | null;
  sr_nearest_resistance?: number | null;
  sr_nearest_support?: number | null;
  sr_52w_high?: number | null;
  // SA-10: signal stability
  stability_days?: number | null;
  // SA-12: regime threshold tier applied
  threshold_tier?: string | null;
  // SA-27: OOS accuracy suppression flag
  ml_oos_suppressed?: boolean;
  low_oos_accuracy?: boolean;
  // H3: additional context factors
  breadth_compression?: number | null;
  pullback_recovery?: string | null;
  news_sentiment_flag?: string | null;
  rs_flag?: string | null;
  sector_headwind?: boolean | null;
  short_interest_flag?: string | null;
  analyst_momentum?: string | null;
  analyst_momentum_adj?: number | null;
  // T223: outcome-based calibrated win rate from signal_outcomes
  calibrated_win_rate?: number | null;
  // T220: institutional intelligence suite
  insider_cluster?: boolean;
  insider_buy_usd?: number | null;
  congress_buy?: boolean;
  sector_momentum?: number | null;
  squeeze_score?: number | null;
  piotroski_score?: number | null;
  macro_blackout?: string | null;
  eps_revision_direction?: number | null;
  // T220-E: 13F institutional ownership
  inst_change_pct?: number | null;
  inst_ownership_increased?: boolean;
};

type Factor = { label: string; bullish: boolean; detail: string; warning?: boolean };

function buildReasons(r: Reasons): Factor[] {
  const factors: Factor[] = [];

  // Earnings proximity — shown first when present
  if (r.earnings_warning === 'critical' || r.earnings_warning === 'short_imminent_event') {
    factors.push({
      label: 'Earnings in ≤2 Days',
      bullish: false,
      warning: true,
      detail: `Earnings report due in ${r.days_to_earnings}d — signal compressed, avoid new entries`,
    });
  } else if (r.earnings_warning === 'caution') {
    factors.push({
      label: `Earnings in ${r.days_to_earnings}d`,
      bullish: false,
      warning: true,
      detail: 'Approaching earnings — signal strength reduced, position sizing caution advised',
    });
  } else if (r.earnings_warning === 'watch') {
    factors.push({
      label: `Earnings in ${r.days_to_earnings}d`,
      bullish: false,
      warning: true,
      detail: 'Earnings approaching — elevated uncertainty, reduce position size and tighten stop',
    });
  } else if (r.earnings_warning === 'note') {
    factors.push({
      label: `Earnings in ${r.days_to_earnings}d`,
      bullish: false,
      detail: 'Earnings within 10 days — slightly elevated uncertainty factored in',
    });
  }

  // Market regime — shown first if bear or high_vol
  if (r.market_regime === 'bear') {
    factors.push({
      label: 'Market Regime',
      bullish: false,
      warning: true,
      detail: 'S&P 500 below 200MA — bear market, higher BUY threshold applied',
    });
  } else if (r.market_regime === 'high_vol') {
    factors.push({
      label: 'High Volatility',
      bullish: false,
      warning: true,
      detail: `Fear & Greed ${r.fear_greed_score != null ? r.fear_greed_score.toFixed(0) : '—'}/100 — market stress, BUY threshold raised and signal compressed`,
    });
  }

  // ML-TA conflict warning
  if (r.ml_ta_conflict) {
    factors.push({
      label: 'ML-TA Conflict',
      bullish: false,
      detail: `ML model and TA indicators strongly disagree — ML weight reduced, signal less reliable`,
    });
  }

  // ADX choppy compression
  if (r.adx_compression) {
    factors.push({
      label: `ADX ${r.adx != null ? r.adx.toFixed(0) : '—'}: Choppy`,
      bullish: false,
      detail: 'ADX below 20 — no clear trend, signal compressed toward neutral',
    });
  }

  // Death cross warning
  if (r.death_cross_event) {
    factors.push({
      label: 'Death Cross',
      bullish: false,
      warning: true,
      detail: 'SMA50 just crossed below SMA200 — major bearish signal',
    });
  }

  // Weekly timeframe alignment
  if (r.weekly_alignment != null) {
    const wRsi = r.weekly_rsi != null ? `RSI ${Math.round(r.weekly_rsi)}` : null;
    const wTrend = r.weekly_trend ? `trend ${r.weekly_trend}` : null;
    const wInfo = [wRsi, wTrend].filter(Boolean).join(', ') || `score ${((r.weekly_ta_score ?? 0) * 100).toFixed(0)}%`;
    const gateNote = r.weekly_gate_fired ? ' — BUY gate active' : '';
    factors.push({
      label: r.weekly_alignment ? '✦ Weekly Aligned' : 'Weekly Conflict',
      bullish: r.weekly_alignment,
      detail: r.weekly_alignment
        ? `Weekly agrees with daily — amplified (${wInfo})`
        : `Weekly conflicts with daily — compressed (${wInfo}${gateNote})`,
    });
  }

  // Active chart patterns
  if (r.active_patterns && r.active_patterns.length > 0) {
    const BULLISH_P = new Set(['double_bottom', 'ascending_triangle', 'bull_flag', 'cup_and_handle']);
    const patternNames = r.active_patterns.map(p => p.replace(/_/g, ' ')).join(', ');
    const isBullish = r.active_patterns.some(p => BULLISH_P.has(p));
    factors.push({
      label: 'Chart Pattern',
      bullish: isBullish,
      detail: `Active: ${patternNames}${r.pattern_adjustment != null ? ` (adj: ${r.pattern_adjustment > 0 ? '+' : ''}${(r.pattern_adjustment * 100).toFixed(1)}%)` : ''}`,
    });
  }

  // VWAP
  if (r.price_above_vwap != null) {
    factors.push({
      label: 'VWMA (20d)',
      bullish: r.price_above_vwap,
      detail: r.price_above_vwap
        ? `Price above 20-day VWMA${r.vwma_20 != null ? ` ($${r.vwma_20.toFixed(2)})` : ''} — above volume-weighted average`
        : `Price below 20-day VWMA${r.vwma_20 != null ? ` ($${r.vwma_20.toFixed(2)})` : ''} — below volume-weighted average`,
    });
  }

  // S/R zone context
  if (r.sr_flag && r.sr_flag !== 'neutral') {
    const isBreakout = r.sr_flag === 'breakout_confirmed';
    const isResistance = r.sr_flag === 'at_resistance';
    const isSupport = r.sr_flag === 'at_support';
    const level = isResistance || isBreakout
      ? r.sr_nearest_resistance != null ? `$${r.sr_nearest_resistance.toFixed(2)}` : (r.sr_52w_high != null ? `52w high $${r.sr_52w_high.toFixed(2)}` : '')
      : r.sr_nearest_support != null ? `$${r.sr_nearest_support.toFixed(2)}` : '';
    factors.push({
      label: isBreakout ? '✦ Level Breakout' : isResistance ? 'At Resistance' : 'At Support',
      bullish: isBreakout || isSupport,
      detail: isBreakout
        ? `Price broke above resistance${level ? ` (${level})` : ''} — confirmed level break, signal boosted`
        : isResistance
          ? `Price approaching resistance${level ? ` (${level})` : ''} — signal compressed 15%`
          : `Price near support zone${level ? ` (${level})` : ''} — demand area, small signal boost`,
    });
  }

  // Trend
  if (r.trend_above_sma50 != null) {
    factors.push({
      label: 'Trend (SMA50)',
      bullish: r.trend_above_sma50,
      detail: r.trend_above_sma50
        ? 'Price above 50-day MA — uptrend intact'
        : 'Price below 50-day MA — downtrend in play',
    });
  }

  if (r.sma50_above_sma200 != null) {
    const spreadNote = r.sma50_above_sma200
      ? (r.gc_spread_expanding === false ? ' • spread narrowing ⚠' : r.gc_spread_expanding ? ' • spread expanding' : '')
      : '';
    const spreadPct = r.gc_spread_pct != null ? ` (${(r.gc_spread_pct * 100).toFixed(1)}%)` : '';
    factors.push({
      label: r.golden_cross_event ? '✦ Golden Cross' : `SMA50 vs SMA200${spreadNote}`,
      bullish: r.sma50_above_sma200 && r.gc_spread_expanding !== false,
      warning: r.sma50_above_sma200 && r.gc_spread_expanding === false,
      detail: r.golden_cross_event
        ? `SMA50 just crossed above SMA200${spreadNote}${spreadPct} — long-term bull signal`
        : r.sma50_above_sma200
          ? `SMA50 above SMA200${spreadPct}${r.gc_spread_expanding === false ? ' — gap shrinking, momentum fading' : r.gc_spread_expanding ? ' — gap widening, trend strengthening' : ' — bull regime'}`
          : `SMA50 below SMA200${spreadPct} — bear regime`,
    });
  }

  // RSI
  if (r.rsi != null) {
    const rsi = r.rsi;
    const isIdeal = rsi >= 45 && rsi < 65;
    const isRecovering = rsi >= 35 && rsi < 45;
    const isExtended = rsi >= 65 && rsi < 72;
    const isOverbought = rsi >= 72;
    const isOversold = rsi < 35;
    factors.push({
      label: `RSI ${rsi.toFixed(0)}`,
      bullish: isIdeal || isRecovering || isOversold,
      detail: isOverbought
        ? `RSI ${rsi.toFixed(0)} — overbought (>72), elevated pullback risk`
        : isExtended
          ? `RSI ${rsi.toFixed(0)} — extended but not extreme`
          : isIdeal
            ? `RSI ${rsi.toFixed(0)} — ideal entry zone (45–65)`
            : isRecovering
              ? `RSI ${rsi.toFixed(0)} — recovering from oversold`
              : `RSI ${rsi.toFixed(0)} — oversold (<35), potential reversal`,
    });
  }

  // Stochastic RSI
  if (r.stoch_rsi_k != null) {
    const k = r.stoch_rsi_k * 100;
    const oversold   = r.stoch_rsi_oversold;
    const overbought = r.stoch_rsi_overbought;
    const crossUp    = r.stoch_rsi_cross_up;
    // Bullish: oversold bounce (crossUp from <20) or healthy neutral zone (20–80, not overbought)
    // Warning: overbought (>80) — elevated pullback risk
    const isBullish = (crossUp ?? false) || oversold || (!overbought && !oversold);
    const isWarning = overbought === true;
    factors.push({
      label: `Stoch RSI ${k.toFixed(0)}`,
      bullish: isBullish && !isWarning,
      warning: isWarning,
      detail: crossUp
        ? `%K ${k.toFixed(0)} — just crossed up from oversold (strong entry signal)`
        : oversold
          ? `%K ${k.toFixed(0)} — oversold zone (<20), potential reversal`
          : overbought
            ? `%K ${k.toFixed(0)} — overbought zone (>80), elevated pullback risk`
            : `%K ${k.toFixed(0)} — neutral zone (20–80), healthy momentum`,
    });
  }

  // RSI divergence
  if (r.rsi_divergence && r.rsi_divergence !== 'none') {
    factors.push({
      label: 'RSI Divergence',
      bullish: r.rsi_divergence === 'bullish',
      warning: r.rsi_divergence === 'bearish',
      detail: r.rsi_divergence === 'bearish'
        ? 'Price making higher highs but RSI declining — momentum fading, reversal risk'
        : 'Price making lower lows but RSI recovering — hidden bullish momentum',
    });
  }

  // MACD — use 3-bar slope (macd_hist_expanding) if available, else fall back to macd_rising
  if (r.macd_hist != null) {
    const bullish = r.macd_hist > 0;
    const zeroCross = r.macd_zero_cross_up;
    const expanding = r.macd_hist_expanding !== undefined ? r.macd_hist_expanding : r.macd_rising;
    const fading = r.macd_momentum_fading === true;
    const slopeStr = r.macd_hist_slope != null ? ` slope ${r.macd_hist_slope > 0 ? '+' : ''}${r.macd_hist_slope.toFixed(4)}` : '';
    factors.push({
      label: zeroCross ? '✦ MACD Zero Cross' : fading ? 'MACD (momentum fading ⚠)' : 'MACD',
      bullish: (bullish || (zeroCross ?? false)) && !fading,
      warning: fading,
      detail: zeroCross
        ? `MACD just crossed above zero — trend direction confirmed bullish`
        : fading
          ? `Histogram +${r.macd_hist.toFixed(3)}${slopeStr} — positive but slope declining, momentum exhausting`
          : bullish
            ? `Histogram +${r.macd_hist.toFixed(3)}${expanding ? ' ↑ expanding' : ''}${slopeStr} — bullish momentum`
            : `Histogram ${r.macd_hist.toFixed(3)}${expanding ? ' ↑ recovering' : ' ↓ falling'}${slopeStr} — bearish momentum`,
    });
  }

  // ADX
  if (r.adx != null) {
    const trending = r.adx > 25;
    factors.push({
      label: `ADX ${r.adx.toFixed(0)}`,
      bullish: r.adx_bullish ?? false,
      detail: !trending
        ? `ADX ${r.adx.toFixed(0)} — weak/choppy market, signals less reliable`
        : r.adx_bullish
          ? `ADX ${r.adx.toFixed(0)} — strong bullish trend (+DI > −DI)`
          : `ADX ${r.adx.toFixed(0)} — trending but bearish direction`,
    });
  }

  // OBV
  if (r.obv_trend_bullish != null) {
    factors.push({
      label: 'OBV (Volume)',
      bullish: r.obv_trend_bullish,
      detail: r.obv_trend_bullish
        ? 'On-Balance Volume trending up — volume confirming price direction'
        : 'OBV trending down — volume not confirming the price move',
    });
  }

  // ML
  if (r.ml_probability != null) {
    const pct = (r.ml_probability * 100).toFixed(1);
    const bullish = r.ml_probability > 0.5;
    factors.push({
      label: 'ML Model',
      bullish,
      detail: `XGBoost predicts ${pct}% probability of upward move`,
    });
  }

  // ── Additional context factors (H3) ───────────────────────────────────────

  // Market breadth compression
  if (r.breadth_compression != null && r.breadth_compression < 1.0) {
    const pct = Math.round((1 - r.breadth_compression) * 100);
    factors.push({
      label: `Breadth Compressed −${pct}%`,
      bullish: false,
      warning: r.breadth_compression <= 0.92,
      detail: `Market breadth weak — signal compressed by ${pct}% (small/mid caps lagging)`,
    });
  }

  // Sector headwind
  if (r.sector_headwind === true) {
    factors.push({
      label: 'Sector Headwind',
      bullish: false,
      detail: 'Sector is underperforming — signal confidence reduced',
    });
  }

  // Relative strength vs sector
  if (r.rs_flag && r.rs_flag !== 'in_line_or_leading') {
    factors.push({
      label: 'RS: Lagging Sector',
      bullish: false,
      detail: r.rs_flag === 'lagging_sector_floor_applied'
        ? 'Lagging sector but positive absolute return — floor applied, partial signal'
        : 'Stock underperforming its sector — signal reduced',
    });
  } else if (r.rs_flag === 'in_line_or_leading') {
    factors.push({ label: 'RS: Leading Sector', bullish: true, detail: 'Stock at or above sector performance — no drag on signal' });
  }

  // Analyst momentum
  if (r.analyst_momentum && r.analyst_momentum !== 'neutral') {
    const isBull = r.analyst_momentum === 'strong_upgrade' || r.analyst_momentum === 'mild_upgrade';
    const adj = r.analyst_momentum_adj != null ? ` (${r.analyst_momentum_adj > 0 ? '+' : ''}${(r.analyst_momentum_adj * 100).toFixed(0)}%)` : '';
    factors.push({
      label: isBull ? 'Analyst Upgrades' : 'Analyst Downgrades',
      bullish: isBull,
      detail: `${r.analyst_momentum.replace(/_/g, ' ')} — analyst sentiment ${isBull ? 'improving' : 'worsening'}${adj}`,
    });
  }

  // Short interest
  if (r.short_interest_flag === 'very_high_squeeze_potential') {
    factors.push({ label: 'High Short Interest', bullish: true, detail: 'Very high short interest — squeeze potential if price rises' });
  } else if (r.short_interest_flag === 'elevated_short_interest') {
    factors.push({ label: 'Elevated Short Interest', bullish: false, warning: true, detail: 'Above-average short interest — elevated overhead pressure' });
  }

  // News sentiment
  if (r.news_sentiment_flag === 'strongly_negative') {
    factors.push({ label: 'News: Strongly Negative', bullish: false, warning: true, detail: 'Recent news sentiment strongly negative — signal confidence reduced' });
  } else if (r.news_sentiment_flag === 'negative') {
    factors.push({ label: 'News: Negative', bullish: false, detail: 'Recent news sentiment negative — mild signal headwind' });
  }

  // Pullback recovery
  if (r.pullback_recovery === 'confirmed' || r.pullback_recovery === 'confirmed_vol') {
    factors.push({
      label: r.pullback_recovery === 'confirmed_vol' ? '✦ Pullback Recovery' : 'Pullback Recovery',
      bullish: true,
      detail: r.pullback_recovery === 'confirmed_vol'
        ? 'Pullback recovered with volume confirmation — high-quality entry setup'
        : 'Pullback recovered — signal quality boost applied',
    });
  } else if (r.pullback_recovery === 'no_recovery_yet') {
    factors.push({ label: 'Pullback: No Recovery', bullish: false, detail: 'In pullback with no recovery confirmation yet — wait for bounce' });
  }

  // ── T220: Institutional intelligence suite ────────────────────────────────

  // Macro blackout (T220-D)
  if (r.macro_blackout) {
    factors.push({
      label: 'Macro Blackout',
      bullish: false,
      warning: true,
      detail: `${r.macro_blackout} event within 2h — signal suppressed, avoid new entries`,
    });
  }

  // Insider cluster buy (T220-A)
  if (r.insider_cluster === true) {
    const usd = r.insider_buy_usd != null && r.insider_buy_usd >= 1e6
      ? ` ($${(r.insider_buy_usd / 1e6).toFixed(1)}M total)`
      : r.insider_buy_usd != null ? ` ($${(r.insider_buy_usd / 1e3).toFixed(0)}K total)` : '';
    factors.push({
      label: '✦ Insider Cluster Buy',
      bullish: true,
      detail: `≥2 insiders bought in last 30d${usd} — institutional conviction signal`,
    });
  }

  // Congress buy (T220-H)
  if (r.congress_buy === true) {
    factors.push({
      label: 'Congress Buy',
      bullish: true,
      detail: 'Congressional purchase disclosed in last 60d — public official interest signal',
    });
  }

  // Sector momentum (T220-G)
  if (r.sector_momentum === 1) {
    factors.push({
      label: 'Sector ↑ Rising',
      bullish: true,
      detail: 'Sector K-Score momentum rising — institutional rotation into this sector',
    });
  } else if (r.sector_momentum === -1) {
    factors.push({
      label: 'Sector ↓ Falling',
      bullish: false,
      detail: 'Sector K-Score momentum declining — institutional rotation out of this sector',
    });
  }

  // Squeeze score (T220-C)
  if (r.squeeze_score != null && r.squeeze_score >= 40) {
    factors.push({
      label: `Squeeze ${r.squeeze_score.toFixed(0)}%`,
      bullish: true,
      detail: r.squeeze_score >= 70
        ? `High squeeze score ${r.squeeze_score.toFixed(0)}% — elevated short interest + upward price action creates squeeze risk for shorts`
        : `Elevated squeeze score ${r.squeeze_score.toFixed(0)}% — notable short interest with improving price momentum`,
    });
  }

  // Piotroski F-Score (T220-B)
  if (r.piotroski_score != null) {
    if (r.piotroski_score >= 7) {
      factors.push({
        label: `F9: ${r.piotroski_score}/9 Quality`,
        bullish: true,
        detail: `Piotroski F-Score ${r.piotroski_score}/9 — high-quality balance sheet across profitability, leverage, and efficiency`,
      });
    } else if (r.piotroski_score <= 2) {
      factors.push({
        label: `F: ${r.piotroski_score}/9 Weak`,
        bullish: false,
        detail: `Piotroski F-Score ${r.piotroski_score}/9 — deteriorating fundamentals across multiple dimensions`,
      });
    }
  }

  // EPS revision direction (T220-F)
  if (r.eps_revision_direction === 1) {
    factors.push({
      label: 'EPS Estimates ↑',
      bullish: true,
      detail: 'Analyst EPS estimates trending upward — positive revision momentum (PEAD effect)',
    });
  } else if (r.eps_revision_direction === -1) {
    factors.push({
      label: 'EPS Estimates ↓',
      bullish: false,
      detail: 'Analyst EPS estimates trending downward — negative revision momentum headwind',
    });
  }

  if (r.inst_ownership_increased === true && r.inst_change_pct != null) {
    factors.push({
      label: `Inst Holdings +${r.inst_change_pct.toFixed(1)}% QoQ`,
      bullish: true,
      detail: `Institutional 13F filings show ${r.inst_change_pct.toFixed(1)}% increase in shares held quarter-over-quarter — smart money accumulating`,
    });
  }

  return factors;
}

export default function SignalCard({ signal }: { signal: Signal }) {
  const reasons = signal.reasons as Reasons;
  const factors = buildReasons(reasons ?? {});
  const taScore = reasons?.ta_score;
  const regime  = reasons?.market_regime;

  return (
    <div className="rounded-md border border-slate-800 bg-slate-900 p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-slate-300">AI Signal</h3>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          {regime === 'bear' && (
            <span style={{ fontSize: '9px', fontWeight: 700, color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', padding: '1px 6px', borderRadius: '4px' }}>
              BEAR MKT
            </span>
          )}
          {reasons?.threshold_tier === 'bear' && (
            <span title="Bear/high-vol regime: tighter BUY threshold applied (0.72 vs 0.65 bull)" style={{ fontSize: '9px', fontWeight: 700, color: '#f97316', background: 'rgba(249,115,22,0.08)', border: '1px solid rgba(249,115,22,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              TIGHT
            </span>
          )}
          {reasons?.low_oos_accuracy && (
            <span title="ML model cross-validation accuracy < 52% — predictions are near coin-flip; signal relies more heavily on TA" style={{ fontSize: '9px', fontWeight: 700, color: '#eab308', background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.3)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              LOW ML CONF
            </span>
          )}
          {reasons?.stability_days != null && reasons.stability_days > 0 && (
            <span title={`Signal unchanged for ${reasons.stability_days} consecutive day${reasons.stability_days === 1 ? '' : 's'}`} style={{ fontSize: '9px', fontWeight: 700, color: '#94a3b8', background: 'rgba(148,163,184,0.08)', border: '1px solid rgba(148,163,184,0.2)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              {reasons.stability_days}d stable
            </span>
          )}
          {/* T220: Institutional intelligence chips */}
          {reasons?.macro_blackout && (
            <span title={`Macro event within 2h: ${reasons.macro_blackout}`} style={{ fontSize: '9px', fontWeight: 700, color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              MACRO BLACKOUT
            </span>
          )}
          {reasons?.insider_cluster === true && (
            <span title="≥2 insiders bought in last 30 days (Form 4 EDGAR)" style={{ fontSize: '9px', fontWeight: 700, color: '#fbbf24', background: 'rgba(251,191,36,0.1)', border: '1px solid rgba(251,191,36,0.3)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              Insider Buy
            </span>
          )}
          {reasons?.congress_buy === true && (
            <span title="Congressional purchase disclosed in last 60 days" style={{ fontSize: '9px', fontWeight: 700, color: '#60a5fa', background: 'rgba(96,165,250,0.1)', border: '1px solid rgba(96,165,250,0.3)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              Congress Buy
            </span>
          )}
          {reasons?.sector_momentum === 1 && (
            <span title="Sector K-Score momentum rising — institutional rotation into sector" style={{ fontSize: '9px', fontWeight: 700, color: '#4ade80', background: 'rgba(74,222,128,0.1)', border: '1px solid rgba(74,222,128,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              Sector ↑
            </span>
          )}
          {reasons?.sector_momentum === -1 && (
            <span title="Sector K-Score momentum declining — institutional rotation out of sector" style={{ fontSize: '9px', fontWeight: 700, color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              Sector ↓
            </span>
          )}
          {reasons?.squeeze_score != null && reasons.squeeze_score >= 40 && (
            <span
              title={`Squeeze score ${reasons.squeeze_score.toFixed(0)}% — short interest + price momentum composite`}
              style={{
                fontSize: '9px', fontWeight: 700,
                color: reasons.squeeze_score >= 70 ? '#fb923c' : '#fbbf24',
                background: reasons.squeeze_score >= 70 ? 'rgba(251,146,60,0.1)' : 'rgba(251,191,36,0.1)',
                border: `1px solid ${reasons.squeeze_score >= 70 ? 'rgba(251,146,60,0.3)' : 'rgba(251,191,36,0.3)'}`,
                padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap',
              }}
            >
              Squeeze {reasons.squeeze_score.toFixed(0)}%
            </span>
          )}
          {reasons?.piotroski_score != null && reasons.piotroski_score >= 7 && (
            <span title={`Piotroski F-Score ${reasons.piotroski_score}/9 — high-quality fundamentals`} style={{ fontSize: '9px', fontWeight: 700, color: '#4ade80', background: 'rgba(74,222,128,0.1)', border: '1px solid rgba(74,222,128,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              F9:{reasons.piotroski_score}
            </span>
          )}
          {reasons?.piotroski_score != null && reasons.piotroski_score <= 2 && (
            <span title={`Piotroski F-Score ${reasons.piotroski_score}/9 — weak fundamentals`} style={{ fontSize: '9px', fontWeight: 700, color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              F:{reasons.piotroski_score}
            </span>
          )}
          {reasons?.inst_ownership_increased === true && reasons?.inst_change_pct != null && (
            <span title={`Institutional 13F: +${(reasons.inst_change_pct as number).toFixed(1)}% QoQ — institutional accumulation`} style={{ fontSize: '9px', fontWeight: 700, color: '#34d399', background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.3)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              Inst ↑{(reasons.inst_change_pct as number).toFixed(0)}%
            </span>
          )}
          <span className={`rounded px-2.5 py-0.5 text-sm font-bold text-white ${SIGNAL_COLOR[signal.signal]}`}>
            {signal.signal}
          </span>
        </div>
      </div>

      {/* Scores */}
      <div className="grid grid-cols-3 gap-2 mb-3">
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100" title="TA composite score (0–100): higher = stronger conviction">{(signal.confidence ?? 0).toFixed(0)}%</div>
          <div className="text-xs text-slate-500">Confidence</div>
        </div>
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100">{(signal.bullish_probability * 100).toFixed(0)}%</div>
          <div className="text-xs text-slate-500">Bullish</div>
        </div>
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100">{signal.horizon}</div>
          <div className="text-xs text-slate-500">Horizon</div>
        </div>
      </div>

      {/* Confidence bar */}
      <div className="h-1 rounded-full bg-slate-800 mb-3 overflow-hidden">
        <div
          className={`h-full rounded-full ${signal.signal === 'BUY' ? 'bg-green-500' : signal.signal === 'SELL' ? 'bg-red-500' : signal.signal === 'WAIT' ? 'bg-orange-500' : 'bg-yellow-500'}`}
          style={{ width: `${signal.bullish_probability * 100}%` }}
        />
      </div>

      {/* T223: Historical win rate from outcome calibration */}
      {reasons?.calibrated_win_rate != null && (
        <div className="flex items-center justify-between mb-3 px-1">
          <span
            className="text-xs text-slate-500"
            title="Win rate for signals at this confidence level — from last 180 days of signal outcomes"
          >
            Historical win rate
          </span>
          <span
            className={`text-xs font-semibold ${
              reasons.calibrated_win_rate >= 0.55
                ? 'text-green-400'
                : reasons.calibrated_win_rate >= 0.48
                ? 'text-amber-400'
                : 'text-slate-400'
            }`}
          >
            {(reasons.calibrated_win_rate * 100).toFixed(0)}%
          </span>
        </div>
      )}

      {/* Reasoning factors */}
      {factors.length > 0 && (
        <div className="space-y-1.5">
          <div className="text-xs font-medium text-slate-400 mb-1">Why this signal:</div>
          {factors.map((f, i) => (
            <div key={i} className="flex items-start gap-2">
              <span style={{
                marginTop: '2px', flexShrink: 0, fontSize: '11px', fontWeight: 700,
                color: f.warning ? '#f97316' : f.bullish ? '#4ade80' : '#f87171',
              }}>
                {f.warning ? '⚠' : f.bullish ? '▲' : '▼'}
              </span>
              <div>
                <span className="text-xs font-medium text-slate-300">{f.label}:</span>{' '}
                <span className="text-xs text-slate-500">{f.detail}</span>
              </div>
            </div>
          ))}
          {/* Pillar score bars — show when at least 2 pillar scores are present */}
          {reasons && (reasons.pillar_trend != null || reasons.pillar_momentum != null) && (() => {
            const pillars = [
              { label: 'Trend',     val: reasons.pillar_trend },
              { label: 'Momentum',  val: reasons.pillar_momentum },
              { label: 'Volume',    val: reasons.pillar_volume },
              { label: 'Structure', val: reasons.pillar_structure },
            ].filter(p => p.val != null) as { label: string; val: number }[];
            return (
              <div style={{ marginTop: 8, paddingTop: 8, borderTop: '1px solid #1e293b' }}>
                <div style={{ fontSize: 9, color: '#334155', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 5 }}>Pillar Scores</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
                  {pillars.map(p => {
                    const pct = Math.round(p.val * 100);
                    const col = p.val >= 0.6 ? '#4ade80' : p.val >= 0.4 ? '#fbbf24' : '#f87171';
                    return (
                      <div key={p.label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        <span style={{ fontSize: 9, color: '#475569', width: 54, flexShrink: 0 }}>{p.label}</span>
                        <div style={{ flex: 1, height: 4, background: '#1e293b', borderRadius: 2, overflow: 'hidden' }}>
                          <div style={{ width: `${pct}%`, height: '100%', background: col, borderRadius: 2 }} />
                        </div>
                        <span style={{ fontSize: 9, color: col, width: 24, textAlign: 'right', flexShrink: 0 }}>{pct}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })()}
          {taScore != null && (
            <div className="mt-2 pt-2 border-t border-slate-800 text-xs text-slate-500">
              TA composite score: <span className="text-slate-300 font-medium">{(taScore * 100).toFixed(0)}/100</span>
              {reasons?.ml_probability == null && (
                <span className="ml-2 text-amber-600">· ML unavailable (train model for better accuracy)</span>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
