/**
 * SignalCard — displays the AI signal generated by the signal-engine service.
 *
 * Signal badge colors
 * ───────────────────
 *   BUY   green  (bg-green-600)  — model expects upward move within horizon
 *   HOLD  yellow (bg-yellow-500) — already in a position; do not add or exit
 *   WAIT  amber  (bg-orange-500) — conditions unclear; stand aside
 *   SELL  red    (bg-red-600)    — model expects downward move; exit or short
 *
 * Signal fields
 * ─────────────
 *   signal            BUY | SELL | HOLD | WAIT
 *   confidence        0–100 composite TA score (higher = stronger conviction)
 *   bullish_probability  0–1 XGBoost ML output (displayed as %)
 *   horizon           SWING (days–weeks) | POSITION (weeks–months) | GROWTH (momentum)
 *   reasons           Detailed breakdown object (see Reasons type below)
 *
 * Reasons breakdown (buildReasons)
 * ─────────────────────────────────
 * Factors are rendered as a vertical list, each with a ▲ (bullish) or
 * ▼ (bearish) indicator.  Order of display:
 *   1. Earnings proximity warning  (critical/caution/note) — shown first
 *   2. Market regime (bear market flag)
 *   3. Death cross event
 *   4. Weekly timeframe alignment  (v3: multi-timeframe confirmation)
 *   5. Active chart patterns        (v3: bull_flag, cup_and_handle, etc.)
 *   6. VWAP (20d)                   (v3: price vs institutional average)
 *   7. Trend vs SMA 50
 *   8. SMA 50 vs SMA 200 / Golden Cross
 *   9. RSI (14)
 *  10. Stochastic RSI
 *  11. MACD histogram
 *  12. ADX (trend strength)
 *  13. OBV (volume confirmation)
 *  14. ML Model (XGBoost bullish probability)
 *  15. TA composite score (footer)
 *
 * v3 signal engine enhancements reflected here:
 *   • weekly_alignment / weekly_ta_score  — ±12–15% confidence adjustment
 *   • active_patterns / pattern_adjustment — chart pattern fusion score
 *   • price_above_vwap / vwap_20          — institutional positioning context
 *   • days_to_earnings / earnings_warning — proximity penalty (critical/caution/note)
 */
import type { Signal } from '@/lib/api';

const SIGNAL_COLOR: Record<string, string> = {
  BUY:  'bg-green-600',
  HOLD: 'bg-yellow-500',
  WAIT: 'bg-orange-500',
  SELL: 'bg-red-600',
};

type Reasons = {
  trend_above_sma50?: boolean;
  sma50_above_sma200?: boolean;
  golden_cross_event?: boolean;
  death_cross_event?: boolean;
  rsi?: number | null;
  stoch_rsi_k?: number | null;
  stoch_rsi_oversold?: boolean;
  stoch_rsi_overbought?: boolean;
  stoch_rsi_cross_up?: boolean;
  rsi_divergence?: string;
  macd_hist?: number | null;
  macd_rising?: boolean;
  macd_zero_cross_up?: boolean;
  bb_pct_b?: number | null;
  adx?: number | null;
  adx_bullish?: boolean;
  obv_bullish?: boolean;
  volume_z?: number | null;
  ml_probability?: number | null;
  market_regime?: string;
  ta_score?: number | null;
  // v3 additions
  price_above_vwap?: boolean | null;
  vwap_20?: number | null;
  weekly_ta_score?: number | null;
  weekly_alignment?: boolean | null;
  weekly_rsi?: number | null;
  weekly_trend?: string | null;
  weekly_macd_bull?: boolean | null;
  weekly_gate_fired?: boolean | null;
  active_patterns?: string[];
  pattern_adjustment?: number | null;
  days_to_earnings?: number | null;
  earnings_warning?: string;
  // v4 additions
  ml_ta_conflict?: boolean;
  adx_compression?: boolean;
  high_vol_compression?: boolean;
  fear_greed_score?: number | null;
  // v5 additions
  sr_context?: string | null;
  sr_flag?: string | null;
  sr_nearest_resistance?: number | null;
  sr_nearest_support?: number | null;
  sr_52w_high?: number | null;
  // SA-10: signal stability
  stability_days?: number | null;
  // SA-12: regime threshold tier applied
  threshold_tier?: string | null;
};

type Factor = { label: string; bullish: boolean; detail: string; warning?: boolean };

function buildReasons(r: Reasons): Factor[] {
  const factors: Factor[] = [];

  // Earnings proximity — shown first when present
  if (r.earnings_warning === 'critical') {
    factors.push({
      label: 'Earnings in ≤2 Days',
      bullish: false,
      warning: true,
      detail: `Earnings report due in ${r.days_to_earnings}d — signal compressed, avoid new entries`,
    });
  } else if (r.earnings_warning === 'caution') {
    factors.push({
      label: `Earnings in ${r.days_to_earnings}d`,
      bullish: false,
      warning: true,
      detail: 'Approaching earnings — signal strength reduced, position sizing caution advised',
    });
  } else if (r.earnings_warning === 'note') {
    factors.push({
      label: `Earnings in ${r.days_to_earnings}d`,
      bullish: false,
      detail: 'Earnings within 10 days — slightly elevated uncertainty factored in',
    });
  }

  // Market regime — shown first if bear or high_vol
  if (r.market_regime === 'bear') {
    factors.push({
      label: 'Market Regime',
      bullish: false,
      warning: true,
      detail: 'S&P 500 below 200MA — bear market, higher BUY threshold applied',
    });
  } else if (r.market_regime === 'high_vol') {
    factors.push({
      label: 'High Volatility',
      bullish: false,
      warning: true,
      detail: `Fear & Greed ${r.fear_greed_score != null ? r.fear_greed_score.toFixed(0) : '—'}/100 — market stress, BUY threshold raised and signal compressed`,
    });
  }

  // ML-TA conflict warning
  if (r.ml_ta_conflict) {
    factors.push({
      label: 'ML-TA Conflict',
      bullish: false,
      detail: `ML model and TA indicators strongly disagree — ML weight reduced, signal less reliable`,
    });
  }

  // ADX choppy compression
  if (r.adx_compression) {
    factors.push({
      label: `ADX ${r.adx != null ? r.adx.toFixed(0) : '—'}: Choppy`,
      bullish: false,
      detail: 'ADX below 20 — no clear trend, signal compressed toward neutral',
    });
  }

  // Death cross warning
  if (r.death_cross_event) {
    factors.push({
      label: 'Death Cross',
      bullish: false,
      warning: true,
      detail: 'SMA50 just crossed below SMA200 — major bearish signal',
    });
  }

  // Weekly timeframe alignment
  if (r.weekly_alignment != null) {
    const wRsi = r.weekly_rsi != null ? `RSI ${Math.round(r.weekly_rsi)}` : null;
    const wTrend = r.weekly_trend ? `trend ${r.weekly_trend}` : null;
    const wInfo = [wRsi, wTrend].filter(Boolean).join(', ') || `score ${((r.weekly_ta_score ?? 0) * 100).toFixed(0)}%`;
    const gateNote = r.weekly_gate_fired ? ' — BUY gate active' : '';
    factors.push({
      label: r.weekly_alignment ? '✦ Weekly Aligned' : 'Weekly Conflict',
      bullish: r.weekly_alignment,
      detail: r.weekly_alignment
        ? `Weekly agrees with daily — amplified (${wInfo})`
        : `Weekly conflicts with daily — compressed (${wInfo}${gateNote})`,
    });
  }

  // Active chart patterns
  if (r.active_patterns && r.active_patterns.length > 0) {
    const BULLISH_P = new Set(['double_bottom', 'ascending_triangle', 'bull_flag', 'cup_and_handle']);
    const patternNames = r.active_patterns.map(p => p.replace(/_/g, ' ')).join(', ');
    const isBullish = r.active_patterns.some(p => BULLISH_P.has(p));
    factors.push({
      label: 'Chart Pattern',
      bullish: isBullish,
      detail: `Active: ${patternNames}${r.pattern_adjustment != null ? ` (adj: ${r.pattern_adjustment > 0 ? '+' : ''}${(r.pattern_adjustment * 100).toFixed(1)}%)` : ''}`,
    });
  }

  // VWAP
  if (r.price_above_vwap != null) {
    factors.push({
      label: 'VWAP (20d)',
      bullish: r.price_above_vwap,
      detail: r.price_above_vwap
        ? `Price above 20-day VWAP${r.vwap_20 != null ? ` ($${r.vwap_20.toFixed(2)})` : ''} — institutional support zone`
        : `Price below 20-day VWAP${r.vwap_20 != null ? ` ($${r.vwap_20.toFixed(2)})` : ''} — below average transaction price`,
    });
  }

  // S/R zone context
  if (r.sr_flag && r.sr_flag !== 'neutral') {
    const isBreakout = r.sr_flag === 'breakout_confirmed';
    const isResistance = r.sr_flag === 'at_resistance';
    const isSupport = r.sr_flag === 'at_support';
    const level = isResistance || isBreakout
      ? r.sr_nearest_resistance != null ? `$${r.sr_nearest_resistance.toFixed(2)}` : (r.sr_52w_high != null ? `52w high $${r.sr_52w_high.toFixed(2)}` : '')
      : r.sr_nearest_support != null ? `$${r.sr_nearest_support.toFixed(2)}` : '';
    factors.push({
      label: isBreakout ? '✦ Level Breakout' : isResistance ? 'At Resistance' : 'At Support',
      bullish: isBreakout || isSupport,
      detail: isBreakout
        ? `Price broke above resistance${level ? ` (${level})` : ''} — confirmed level break, signal boosted`
        : isResistance
          ? `Price approaching resistance${level ? ` (${level})` : ''} — signal compressed 15%`
          : `Price near support zone${level ? ` (${level})` : ''} — demand area, small signal boost`,
    });
  }

  // Trend
  if (r.trend_above_sma50 != null) {
    factors.push({
      label: 'Trend (SMA50)',
      bullish: r.trend_above_sma50,
      detail: r.trend_above_sma50
        ? 'Price above 50-day MA — uptrend intact'
        : 'Price below 50-day MA — downtrend in play',
    });
  }

  if (r.sma50_above_sma200 != null) {
    factors.push({
      label: r.golden_cross_event ? '✦ Golden Cross' : 'SMA50 vs SMA200',
      bullish: r.sma50_above_sma200,
      detail: r.golden_cross_event
        ? 'SMA50 just crossed above SMA200 — long-term bull signal'
        : r.sma50_above_sma200
          ? 'SMA50 above SMA200 — bull regime'
          : 'SMA50 below SMA200 — bear regime',
    });
  }

  // RSI
  if (r.rsi != null) {
    const rsi = r.rsi;
    const isIdeal = rsi >= 45 && rsi < 65;
    const isRecovering = rsi >= 35 && rsi < 45;
    const isExtended = rsi >= 65 && rsi < 72;
    const isOverbought = rsi >= 72;
    const isOversold = rsi < 35;
    factors.push({
      label: `RSI ${rsi.toFixed(0)}`,
      bullish: isIdeal || isRecovering || isOversold,
      detail: isOverbought
        ? `RSI ${rsi.toFixed(0)} — overbought (>72), elevated pullback risk`
        : isExtended
          ? `RSI ${rsi.toFixed(0)} — extended but not extreme`
          : isIdeal
            ? `RSI ${rsi.toFixed(0)} — ideal entry zone (45–65)`
            : isRecovering
              ? `RSI ${rsi.toFixed(0)} — recovering from oversold`
              : `RSI ${rsi.toFixed(0)} — oversold (<35), potential reversal`,
    });
  }

  // Stochastic RSI
  if (r.stoch_rsi_k != null) {
    const k = r.stoch_rsi_k * 100;
    const oversold   = r.stoch_rsi_oversold;
    const overbought = r.stoch_rsi_overbought;
    const crossUp    = r.stoch_rsi_cross_up;
    factors.push({
      label: `Stoch RSI ${k.toFixed(0)}`,
      bullish: oversold || (crossUp ?? false),
      detail: crossUp
        ? `%K ${k.toFixed(0)} — just crossed up from oversold (strong entry signal)`
        : oversold
          ? `%K ${k.toFixed(0)} — oversold zone (<20), RSI at a low extreme`
          : overbought
            ? `%K ${k.toFixed(0)} — overbought zone (>80), RSI at a high extreme`
            : `%K ${k.toFixed(0)} — neutral zone`,
    });
  }

  // RSI divergence
  if (r.rsi_divergence && r.rsi_divergence !== 'none') {
    factors.push({
      label: 'RSI Divergence',
      bullish: r.rsi_divergence === 'bullish',
      warning: r.rsi_divergence === 'bearish',
      detail: r.rsi_divergence === 'bearish'
        ? 'Price making higher highs but RSI declining — momentum fading, reversal risk'
        : 'Price making lower lows but RSI recovering — hidden bullish momentum',
    });
  }

  // MACD
  if (r.macd_hist != null) {
    const bullish = r.macd_hist > 0;
    const zeroCross = r.macd_zero_cross_up;
    factors.push({
      label: zeroCross ? '✦ MACD Zero Cross' : 'MACD',
      bullish: bullish || (zeroCross ?? false),
      detail: zeroCross
        ? `MACD just crossed above zero — trend direction confirmed bullish`
        : bullish
          ? `Histogram +${r.macd_hist.toFixed(3)}${r.macd_rising ? ' ↑ rising' : ''} — bullish momentum`
          : `Histogram ${r.macd_hist.toFixed(3)}${r.macd_rising ? ' ↑ recovering' : ' ↓ falling'} — bearish momentum`,
    });
  }

  // ADX
  if (r.adx != null) {
    const trending = r.adx > 25;
    factors.push({
      label: `ADX ${r.adx.toFixed(0)}`,
      bullish: r.adx_bullish ?? false,
      detail: !trending
        ? `ADX ${r.adx.toFixed(0)} — weak/choppy market, signals less reliable`
        : r.adx_bullish
          ? `ADX ${r.adx.toFixed(0)} — strong bullish trend (+DI > −DI)`
          : `ADX ${r.adx.toFixed(0)} — trending but bearish direction`,
    });
  }

  // OBV
  if (r.obv_bullish != null) {
    factors.push({
      label: 'OBV (Volume)',
      bullish: r.obv_bullish,
      detail: r.obv_bullish
        ? 'On-Balance Volume trending up — volume confirming price direction'
        : 'OBV trending down — volume not confirming the price move',
    });
  }

  // ML
  if (r.ml_probability != null) {
    const pct = (r.ml_probability * 100).toFixed(1);
    const bullish = r.ml_probability > 0.5;
    factors.push({
      label: 'ML Model',
      bullish,
      detail: `XGBoost predicts ${pct}% probability of upward move`,
    });
  }

  return factors;
}

export default function SignalCard({ signal }: { signal: Signal }) {
  const reasons = signal.reasons as Reasons;
  const factors = buildReasons(reasons ?? {});
  const taScore = reasons?.ta_score;
  const regime  = reasons?.market_regime;

  return (
    <div className="rounded-md border border-slate-800 bg-slate-900 p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-slate-300">AI Signal</h3>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          {regime === 'bear' && (
            <span style={{ fontSize: '9px', fontWeight: 700, color: '#f87171', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', padding: '1px 6px', borderRadius: '4px' }}>
              BEAR MKT
            </span>
          )}
          {reasons?.threshold_tier === 'bear' && (
            <span title="Bear/high-vol regime: tighter BUY threshold applied (0.72 vs 0.65 bull)" style={{ fontSize: '9px', fontWeight: 700, color: '#f97316', background: 'rgba(249,115,22,0.08)', border: '1px solid rgba(249,115,22,0.25)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              TIGHT
            </span>
          )}
          {reasons?.stability_days != null && reasons.stability_days > 0 && (
            <span title={`Signal unchanged for ${reasons.stability_days} consecutive day${reasons.stability_days === 1 ? '' : 's'}`} style={{ fontSize: '9px', fontWeight: 700, color: '#94a3b8', background: 'rgba(148,163,184,0.08)', border: '1px solid rgba(148,163,184,0.2)', padding: '1px 6px', borderRadius: '4px', whiteSpace: 'nowrap' }}>
              {reasons.stability_days}d stable
            </span>
          )}
          <span className={`rounded px-2.5 py-0.5 text-sm font-bold text-white ${SIGNAL_COLOR[signal.signal]}`}>
            {signal.signal}
          </span>
        </div>
      </div>

      {/* Scores */}
      <div className="grid grid-cols-3 gap-2 mb-3">
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100">{(signal.confidence ?? 0).toFixed(0)}</div>
          <div className="text-xs text-slate-500">Confidence</div>
        </div>
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100">{(signal.bullish_probability * 100).toFixed(0)}%</div>
          <div className="text-xs text-slate-500">Bullish</div>
        </div>
        <div className="text-center">
          <div className="text-lg font-bold text-slate-100">{signal.horizon}</div>
          <div className="text-xs text-slate-500">Horizon</div>
        </div>
      </div>

      {/* Confidence bar */}
      <div className="h-1 rounded-full bg-slate-800 mb-3 overflow-hidden">
        <div
          className={`h-full rounded-full ${signal.signal === 'BUY' ? 'bg-green-500' : signal.signal === 'SELL' ? 'bg-red-500' : signal.signal === 'WAIT' ? 'bg-orange-500' : 'bg-yellow-500'}`}
          style={{ width: `${signal.bullish_probability * 100}%` }}
        />
      </div>

      {/* Reasoning factors */}
      {factors.length > 0 && (
        <div className="space-y-1.5">
          <div className="text-xs font-medium text-slate-400 mb-1">Why this signal:</div>
          {factors.map((f, i) => (
            <div key={i} className="flex items-start gap-2">
              <span style={{
                marginTop: '2px', flexShrink: 0, fontSize: '11px', fontWeight: 700,
                color: f.warning ? '#f97316' : f.bullish ? '#4ade80' : '#f87171',
              }}>
                {f.warning ? '⚠' : f.bullish ? '▲' : '▼'}
              </span>
              <div>
                <span className="text-xs font-medium text-slate-300">{f.label}:</span>{' '}
                <span className="text-xs text-slate-500">{f.detail}</span>
              </div>
            </div>
          ))}
          {taScore != null && (
            <div className="mt-2 pt-2 border-t border-slate-800 text-xs text-slate-500">
              TA composite score: <span className="text-slate-300 font-medium">{(taScore * 100).toFixed(0)}/100</span>
              {reasons?.ml_probability == null && (
                <span className="ml-2 text-amber-600">· ML unavailable (train model for better accuracy)</span>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
